from django.urls import path

from . import views

urlpatterns = [
    path(
        "",
        views.article_list,
        name="article_list",
    ),
    path(
        "article/<int:pk>/",
        views.article_detail,
        name="article_detail",
    ),
    path(
        "articles/new/",
        views.article_create,
        name="article_create",
    ),
    path(
        "articles/mine/",
        views.my_articles,
        name="my_articles",
    ),
    path(
        "articles/<int:pk>/edit/",
        views.article_update,
        name="article_update",
    ),
    path(
        "newsletters/",
        views.newsletter_list,
        name="newsletter_list",
    ),
    path(
        "newsletter/<int:pk>/",
        views.newsletter_detail,
        name="newsletter_detail",
    ),
    path(
        "newsletters/new/",
        views.newsletter_create,
        name="newsletter_create",
    ),
    path(
        "newsletters/<int:pk>/edit/",
        views.newsletter_update,
        name="newsletter_update",
    ),
    path(
        "editor/articles/",
        views.editor_articles,
        name="editor_articles",
    ),
    path(
        "editor/articles/<int:pk>/approve/",
        views.approve_article,
        name="approve_article",
    ),
    path(
        "subscriptions/",
        views.subscriptions,
        name="subscriptions",
    ),
    path(
        "register/",
        views.register,
        name="register",
    ),
    path(
        "login/",
        views.login_view,
        name="login",
    ),
    path(
        "logout/",
        views.logout_view,
        name="logout",
    ),
]
